from __future__ import annotations

from pathlib import Path

import win32com.client as win32


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "DMRGAT_Section_3_2_Algorithm_WordEquations.docx"


SECTION_ITEMS = [
    ("heading1", "3.2 DMRGAT Architecture and Algorithm"),
    (
        "paragraph",
        "The proposed DMRGAT model is designed to transform the dynamic multi-relation industry graph into a set of predictive node representations. Unlike a conventional time-series model that treats each industry independently, DMRGAT explicitly incorporates cross-industry dependence through graph attention. At each trading date t, the model takes the node feature matrix X_t and the fused adjacency matrix A_t as inputs. Each row of X_t corresponds to one industry, and each element of A_t represents the strength of the relation between two industries after integrating return correlation, capital-flow similarity, and static industry linkage. The purpose of the model is to learn a nonlinear mapping from the dynamic graph state (G_t, X_t) to the predicted future excess return for each industry node.",
    ),
    (
        "paragraph",
        "The initial node representation of industry i is defined as follows. This notation indicates that the input of the first graph attention layer is exactly the feature vector constructed in the data preprocessing stage.",
    ),
    ("equation", "h_i^(0)=x_(i,t)"),
    (
        "paragraph",
        "Before computing attention scores, the raw node representation is projected into a hidden feature space through a trainable linear transformation:",
    ),
    ("equation", "z_i=W h_i^(0)"),
    (
        "paragraph",
        "This projection maps heterogeneous financial variables, including returns, volatility, momentum, liquidity-related information, and cross-sectional rankings, into a common latent representation. It also allows the model to learn task-specific combinations of these variables rather than relying directly on their raw scales. In the current implementation, the hidden dimension is set to 32, which is appropriate for a relatively small industry graph with 15 nodes.",
    ),
    (
        "paragraph",
        "For each edge (i, j), the weighted attention score is computed by combining neural attention with the prior graph relation:",
    ),
    ("equation", "e_(ij,t)=A_(ij,t)\\cdot LeakyReLU(a^T [z_i\\Vert z_j])"),
    (
        "paragraph",
        "This equation is the key difference between DMRGAT and a vanilla GAT. In a standard GAT, the attention score is determined only by the transformed node features. In DMRGAT, the score is further multiplied by the fused edge weight A_ij,t. Therefore, the model does not allocate attention in a completely unconstrained manner. Instead, attention allocation is guided by economically meaningful prior relations. Industries with stronger return co-movement, capital-flow similarity, or structural linkage receive greater prior influence in the attention mechanism.",
    ),
    (
        "paragraph",
        "The attention score is then normalized over the neighborhood of node i through a softmax operation:",
    ),
    ("equation", "alpha_(ij,t)=(exp(e_(ij,t)))/(sum_(k\\in N_i) exp(e_(ik,t)))"),
    (
        "paragraph",
        "The normalized coefficient alpha_ij,t can be interpreted as the relative importance of industry j when updating the representation of industry i. Since the coefficients are normalized within the neighborhood, the attention mechanism produces a probability-like distribution over neighboring industries. This makes the model adaptive to local graph structure and allows different industries to depend on different sets of influential neighbors.",
    ),
    (
        "paragraph",
        "Using the normalized attention weights, the first-layer node representation is computed through neighborhood aggregation. In the current implementation, the first graph attention layer uses four attention heads:",
    ),
    ("equation", "h_i^(1)=Concat_(m=1)^4 [sigma(sum_(j\\in N_i) alpha_(ij,t)^(m) z_j^(m))]"),
    (
        "paragraph",
        "The multi-head design is meaningful in the sector-rotation setting because industry relationships are heterogeneous. One head may learn cyclical co-movement, another may capture technology-sector spillovers, while another may focus on financial or consumption-related linkages. Instead of forcing all relations into a single attention distribution, the model allows different heads to represent different relational perspectives. The head-specific attention heatmaps generated by the implementation provide an interpretable view of these different relational patterns.",
    ),
    (
        "paragraph",
        "After the first graph attention layer, the concatenated representation is normalized, passed through a nonlinear activation, and regularized by dropout. The resulting representation is then passed into a second graph attention layer with one attention head. Conceptually, the first layer aggregates information from directly connected neighboring industries, while the second layer further integrates the information already propagated through the first layer. Therefore, a two-layer GAT structure allows each industry node to incorporate both first-order neighborhood information and higher-order relational signals transmitted through neighboring industries.",
    ),
    ("equation", "h_i^(2)=sigma(sum_(j\\in N_i) alpha_(ij,t)^(2) W^(2) h_j^(1))"),
    (
        "paragraph",
        "Here, the superscript in h_i^(1) and h_i^(2) denotes the graph attention layer index rather than the number of training iterations. This distinction is important because the model depth describes representation transformations during one forward pass, while optimization iterations refer to repeated parameter updates during training.",
    ),
    ("paragraph", "The final prediction is obtained through a linear regression head:"),
    ("equation", "\\hat y_(i,t)^(30)=W_o h_i^(2)"),
    (
        "paragraph",
        "The output is a continuous estimate of the future 30-day excess return of industry i. This design is more suitable for investment applications than a simple binary classification output because portfolio allocation usually depends on relative expected returns. A continuous prediction can be ranked across industries, transformed into allocation weights, or combined with risk-control rules.",
    ),
    (
        "paragraph",
        "The training objective is aligned with this ranking-based interpretation. Instead of relying purely on mean squared error, the model uses a hybrid loss that combines pairwise ranking loss and a weak regression regularization term. For one graph snapshot, the ranking loss is defined as",
    ),
    ("equation", "L_rank=mean_(i,j) log(1+exp(-(y_i-y_j)(\\hat y_i-\\hat y_j)))"),
    (
        "paragraph",
        "This loss penalizes incorrect ordering between industry pairs. If industry i realizes a higher future excess return than industry j, the model is encouraged to assign a higher predicted value to industry i. Thus, the loss directly reflects the cross-sectional ranking objective that is central to sector rotation.",
    ),
    ("equation", "L_mse=1/N sum_i (\\hat y_i-y_i)^2"),
    ("paragraph", "The total loss used in the current implementation is"),
    ("equation", "L=4.0 L_rank+0.05 L_mse"),
    (
        "paragraph",
        "The relatively large weight on the ranking loss reflects the investment objective of identifying relative sector strength, while the small MSE term helps stabilize the numerical scale of the predicted excess returns. The parameters of the model, including the linear projection matrices, attention vectors, biases, and output regression weights, are optimized using Adam with early stopping based on validation performance.",
    ),
    (
        "paragraph",
        "Overall, the DMRGAT algorithm can be summarized as a dynamic graph-based representation learning procedure. For each trading date, the model constructs a multi-relation graph, projects industry features into a hidden space, computes edge-weighted attention scores, aggregates neighboring information through multi-head graph attention, applies a second graph attention layer for higher-order integration, and finally predicts future excess returns through a regression head. This architecture is consistent with the financial intuition that sector performance depends not only on each industry's own characteristics but also on the evolving relational structure among industries.",
    ),
]


def insert_paragraph(selection, text: str, bold: bool = False) -> None:
    selection.Font.Name = "Times New Roman"
    selection.Font.Size = 11
    selection.Font.Bold = bold
    selection.TypeText(text)
    selection.TypeParagraph()
    selection.Font.Bold = False


def insert_equation(word, document, selection, linear: str) -> None:
    selection.ParagraphFormat.Alignment = 1
    selection.Font.Name = "Cambria Math"
    selection.Font.Size = 11
    start = selection.Start
    selection.TypeText(linear)
    end = selection.End
    rng = document.Range(start, end)
    omath = document.OMaths.Add(rng)
    omath.BuildUp()
    selection.SetRange(omath.Range.End, omath.Range.End)
    selection.TypeParagraph()
    selection.ParagraphFormat.Alignment = 0
    selection.Font.Name = "Times New Roman"


def main() -> None:
    if OUTPUT_PATH.exists():
        OUTPUT_PATH.unlink()

    word = win32.DispatchEx("Word.Application")
    word.Visible = False
    word.DisplayAlerts = 0
    document = word.Documents.Add()
    selection = word.Selection

    try:
        for kind, text in SECTION_ITEMS:
            if kind == "heading1":
                insert_paragraph(selection, text, bold=True)
            elif kind == "paragraph":
                insert_paragraph(selection, text)
            elif kind == "equation":
                insert_equation(word, document, selection, text)
            else:
                raise ValueError(kind)
        document.SaveAs(str(OUTPUT_PATH))
    finally:
        document.Close(SaveChanges=False)
        word.Quit()

    print(f"Saved: {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
